name: BAOEnv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - scipy
  - cython
  - gsl
  - llvm-openmp
  - c-compiler
  - cxx-compiler
  - fftw
  - mpi4py
  - openmpi
  - matplotlib
  - pandas
  - pip
  - pip:
      - classy
      - cobaya
      - camb
      - jax
      - jaxlib
      - iminuit
      - "pycorr @ git+https://github.com/cosmodesi/pycorr"
      - "desilike[plotting,jax] @ git+https://github.com/cosmodesi/desilike@152d3a545d793deffd59bcce543dc9f2f9ab9869"
      - "pyclass @ git+https://github.com/adematti/pyclass"
      - anesthetic
      - zeus-mcmc